import requests
import time
import random
import argparse
import sys

def simulate_device(device_id, api_key, server_url, interval, timestamp=None):
    """
    Simulates an IoT device (like an ESP32) reading soil metrics and sending them securely to the backend.
    """
    url = f"{server_url}/api/iot/ingest/"
    headers = {
        "Content-Type": "application/json",
        "X-API-KEY": api_key
    }

    print(f"📡 Starting IoT Simulation for Device: {device_id}")
    print(f"🌍 Endpoint: {url}")
    print("-" * 40)

    try:
        while True:
            # Simulate generic sensor data
            humidite_sol = round(random.uniform(20.0, 60.0), 2)
            temperature_sol = round(random.uniform(15.0, 35.0), 2)
            # NPK (Nitrogen, Phosphorus, Potassium) mock values
            n_val = round(random.uniform(10.0, 50.0), 2)
            p_val = round(random.uniform(5.0, 20.0), 2)
            k_val = round(random.uniform(15.0, 40.0), 2)

            payload = {
                "device_id": device_id,
                "humidite_sol": humidite_sol,
                "temperature_sol": temperature_sol,
                "N": n_val,
                "P": p_val,
                "K": k_val
            }
            
            if timestamp:
                payload["timestamp"] = timestamp

            print(f"⏳ Sending Data: Hum={humidite_sol}%, Temp={temperature_sol}°C...")
            
            try:
                response = requests.post(url, json=payload, headers=headers)
                
                if response.status_code == 201:
                    data = response.json()
                    action = data.get("action", {})
                    pump_on = action.get("pump_on", False)
                    water_liters = action.get("water_liters", 0)
                    
                    if pump_on:
                        print(f"✅ Success! Backend responded. [ACTION]: 💧 PUMP ON ({water_liters}L required).")
                    else:
                        print(f"✅ Success! Backend responded. [ACTION]: 🛑 PUMP OFF (Sufficient moisture).")
                else:
                    print(f"❌ Failed! Status Code: {response.status_code}. Response: {response.text}")

            except requests.exceptions.RequestException as e:
                print(f"⚠️ Connection Error: {e}")

            print(f"💤 Sleeping for {interval} seconds...\n")
            time.sleep(interval)

    except KeyboardInterrupt:
        print("\n🛑 Simulation stopped by user.")
        sys.exit(0)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Smart Irrigation IoT Simulator")
    parser.add_argument("--device_id", required=True, help="Unique Device ID registered in the backend")
    parser.add_argument("--api_key", required=True, help="API Key generated by the backend for this device")
    parser.add_argument("--url", default="http://127.0.0.1:8000", help="Base URL of the Django backend")
    parser.add_argument("--interval", type=int, default=10, help="Interval between readings in seconds")
    parser.add_argument("--timestamp", type=str, default=None, help="Optional timestamp (ISO format) for past data generation")
    
    args = parser.parse_args()
    simulate_device(args.device_id, args.api_key, args.url, args.interval, args.timestamp)



    # commande pour lancer le script python simulateur_iot.py --device_id MON_ESP32_1 --api_key la_clé_secrete_ici --interval 10


    