# Generated by Django 5.2.12 on 2026-04-22 11:52

import capteurs.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capteur',
            name='api_key',
            field=models.CharField(blank=True, default=capteurs.models.generate_api_key, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='capteur',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lecturecapteur',
            name='K',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='lecturecapteur',
            name='N',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='lecturecapteur',
            name='P',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='lecturecapteur',
            name='humidite_sol',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
