# Generated by Django 4.2.30 on 2026-04-23 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capteurs', '0002_capteur_api_key_capteur_device_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturecapteur',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
