# Generated by Django 5.2.12 on 2026-04-18 22:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('superficie_ha', models.FloatField()),
                ('type_plante', models.CharField(max_length=100)),
                ('stade', models.CharField(choices=[('jeune', 'Jeune'), ('mature', 'Mature'), ('fin', 'Fin')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('ville', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
