# Generated by Django 5.2.12 on 2026-04-18 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcelles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonneeMeteo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('T_min', models.FloatField()),
                ('T_max', models.FloatField()),
                ('pluie_mm', models.FloatField()),
                ('mois', models.IntegerField()),
                ('date', models.DateField()),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meteo_data', to='parcelles.parcelle')),
            ],
        ),
    ]
